### ISSUE TITLE
The registry doesn't delete the stopped service instance

### ISSUE THREAD

**Issue by PanPain** [DescartesResearch/TeaStore#115]
In the process of dynamically adding or subtracting service instances, the address of the service instance that is stopped still exists in the registry. Check the log of the registry and throw the following exception. I think it is because the LinkedList  isn't thread safe. How can I solve this problem?
![image](https://user-images.githubusercontent.com/16000371/56646974-36700180-66b3-11e9-8f9a-ecf64fa5031a.png)

**Comment by SimonEismann** [comment]
Dynamically adding and removing services is suported. In this case, the registry stops removing dead services, because the daemon responsible for this crashed due to the ConcurrentModificationException. Could you provide the ~5 lines in the log prior to the exception? This would help to track this issue down.

**Comment by SimonEismann** [comment]
@PanPain This issue should be fixed with TeaStore v1.3.2, however, we could only perform light testing on this as we were not able to reproduce the issue. Could you please confirm that this solved the issue?
