### ISSUE TITLE
Using Netflix Eureka regsitry

### ISSUE THREAD

**Issue by SyCode7** [DescartesResearch/TeaStore#119]
I'd like to use [Netflix Eureka Registry](https://github.com/Netflix/eureka) in place of the pre-configured registry for TeaStore. Will this be possible `out-of-the-box` or requires some changes or not even possible/advised. There are security features I integrated into a customized  Eureka registry ([available in this repository](https://github.com/maineffort/SecurityGateway)). It will be cool to try out those features on TeaStore to thus enabling security testing in dev pipelines.

**Comment by SimonEismann** [comment]
We do not support Eureka out of the box, so this does require some adaptation. Two things need to be changed: (1) the calls to our service registry API  need to be replaced with the Eureka API (2) In our implementation, the registration call doubles as the heartbeat. For Eureka those are different things that requires some minor changes. As far as I can tell right now you would need to change the following things: 

In `tools.descartes.teastore.registryclient.RegistryClient`:
-  `getServersForService()` should use the Eureka API to get all instances for a service
- `register()/unregister()` should register/unregister to the Eureka API either once or until Eureka returns a positive result depending on the required level of resilience
In `tools.descartes.teastore.registryclient.RegistryClient`:
- `run()` should ping the Eureka heartbeat API instead of registering.

After these adaptations you can follow the instructions here: https://github.com/DescartesResearch/TeaStore/wiki/Building-the-TeaStore to build the containers. Then if the environment variables REGISTRY_HOST and REGISTRY_PORT point to a Eureka instance, everything should work fine. Let me know if you attempt this and run into any trouble.

**Comment by SimonEismann** [comment]
closed until further notice
