### ISSUE TITLE
Latest WebUI image doesn't match the code on master branch

### ISSUE THREAD

**Issue by msnteixeira** [DescartesResearch/TeaStore#178]
When building the [descartesresearch/teastore-webui:latest image](https://hub.docker.com/layers/descartesresearch/teastore-webui/latest/images/sha256-a22920057ef41fdd0936a970ac93b60c21e3237fc812de00318092d3bbc93ea5?context=explore) from DockerHub, the deployment works fine using HTTP. 

However when building from the code, because the Cookie.setSecure flag is set to True, for example [here](https://github.com/DescartesResearch/TeaStore/blob/358dd2ffb934ff92c588c06deb6b9d5bf0664a0d/services/tools.descartes.teastore.webui/src/main/java/tools/descartes/teastore/webui/servlet/AbstractUIServlet.java#L170), the deployment using HTTP no longer works when doing actions that require cookies such like adding teas to the cart. 

From our point of view, the code needs to match the latest WebUI image.

**Comment by SimonEismann** [comment]
In terms of master branch vs image content, our philosophy currently is that we only build the images for current releases, so the current image matches to the content of the commit tagged for version 1.3.8 (see https://github.com/DescartesResearch/TeaStore/tags). So if you are looking to customize something and compare it to the 1.3.8 image, you could checkout the corresponding commit and adapt it. Is there any specific need from our end to have the current state of the master branch match the image?

In regard to the secure cookies breaking the WebUI, I'll quickly test if I can reproduce this issue and then switch back to unsecured cookies. Thanks for letting us know about this issue, otherwise this breaking bug would have probably made its way into v1.3.9 :)

**Comment by SimonEismann** [comment]
I was able to replicate this issue and therefore removed the secure cookies again :-)

Thanks for reaching out about this, feel free to reopen this issue in case there are any further issues
